package org.bukkit;
public enum Sound {
    ENTITY_GENERIC_DRINK, ENTITY_WITHER_SPAWN, ITEM_TRIDENT_THUNDER,
    ENTITY_FIREWORK_ROCKET_LAUNCH, ENTITY_EXPERIENCE_ORB_PICKUP,
    ENTITY_LIGHTNING_BOLT_THUNDER, BLOCK_ANVIL_LAND;
}
